# safelist
branches:
  only:
    - master
notifications:
  email:
    on_success: never
cache:
  directories:
  # - "/tmp/texlive"
  # - "$HOME/.texlive"
  # - "$HOME/.cache/pip"
script:
- bash dropbox_uploader.sh download Apps/Overleaf/phd_thesis/gitHeadLocal.gin gitHeadLocal.gin
- cp icc_profiles/sRGB_IEC61966-2-1_black_scaled.icc /tmp/texlive/texmf-dist/tex/latex/pdfx/
- texhash
# - latexmk -f --shell-escape --bibtex -pdf -interaction=nonstopmode -halt-on-error main.tex # force making the pdf
- latexmk -f --shell-escape --bibtex -pdf -quiet -silent -interaction=batchmode -halt-on-error main.tex # force making the pdf
# - latexmk --shell-escape --bibtex -pdf -quiet -silent -interaction=batchmode -halt-on-error main.tex
# - latexmk -f --shell-escape --bibtex -pdf main.tex # debug purposes (be verbose)
- "./dropbox_uploader.sh upload main.pdf Apps/phd_thesis_CI_build_output/${TRAVIS_BRANCH}/main-latest.pdf"
- "./dropbox_uploader.sh upload main.pdf Apps/phd_thesis_CI_build_output/${TRAVIS_BRANCH}/historic_versions/main-${TRAVIS_COMMIT}.pdf"
before_install:
# - rm -rf /tmp/texlive
# - rm -rf $HOME/.texlive
- echo $super_secret_password | gpg --passphrase-fd 0 .dropbox_uploader.gpg
- mv .dropbox_uploader ~/
- cd ..
- cp -R phd_thesis/ copy_repo/
- cd copy_repo
- rm -rf .git
- curl "https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh" -o dropbox_uploader.sh
- chmod +x dropbox_uploader.sh
install:
- source ./texlive_install.sh
- pip install --user pip
- pip install --user Pygments
- rsync -rvzctlp rsync://contextgarden.net/distribution/current/bin/luatex/linux-64/bin/ /tmp/texlive/bin/x86_64-linux/
- fmtutil -user --byengine luatex
- fmtutil -user --all
- texhash
env:
  global:
    secure: oeNBy31e33khf2pJ9Pcu7jRqkohP6REswQgdtwEHOW/OIcyieNe8ZTn5i81leMhoLCkHdGQH2jZfO10JREJzK+ycOQew5yeQ1/LGtF3kOhjX6322t0WfNMM2/XlJntCiHOGrWp+C0IbqYPisyLmK5Ta3bE5L6VepykRtz1TyQM0dsON8E9J7dZZs7TPbWkTRXabFwip+MygZLugvGkihfgVKgQUU3XXjEd+jrNyDUL1xp9qMdxqASfD2dj9dSEzoQ5qGW4Sp3Paw4AHGaEDfDBbfGYUjJwL2rOchrmUotPYnY57IBPjNrOMeommBGJbZrn4HeSDhdTXOdXMvid7//WRuBzGMmZEJbI+2fshLip2KX3t6dnqF8ynGBmbR1RWqsdCnuiSOekixQPMCBjIMgLDH2AJcE8NGLxRUGhZW/pWSZcvr7ZpGc8liriCwGG6vwwEtQBTyhJMa7Xj+O9UHl1ruYDC+DC17gDLlpHX2G922cappLxSgbJF8NMZEsa7IlUzzadXLE2rTcVLwiNeAlc+WAtHOlPY2gGk+aPF8exRUDi9XqzP6oa9johYkg+EP1zAkN43Ss99FDl1ChQPZnNpLVUSNPfys3XCPlmkSSM8bdgfP0ftz++y59X0Nkyii9A8f7HDgwmzrZav7GeXKZC2z08Looi6SFfDVSEIp2a8=
