function custom_m2t_fcn(filename,figwidth_mm,standalone_flag)

figheight_mm = figwidth_mm/1.618; % mm 

cleanfigure;
matlab2tikz([filename    , '.tikz'],                       ...
            'showInfo'   , false,                          ...
            'width'      , [num2str(figwidth_mm),  'mm'],  ...
            'height'     , [num2str(figheight_mm), 'mm'],  ...
            'floatFormat', '%.6g',                         ...
            'standalone' , standalone_flag);