#!/usr/bin/env sh

tlmgr install   \
    algorithmicx \
    algorithms \
    anyfontsize \
    appendix \
    arydshln \
    bezos \
    biber \
    biblatex \
    bigints \
    booktabs \
    cancel \
    caption \
    ccicons \
    chemformula \
    cleveref \
    colorprofiles \
    csquotes \
    ctablestack \
    datatool \
    datetime \
    datetime2 \
    datetime2-english \
    dehyph-exptl \
    diffcoeff \
    doclicense \
    enumitem \
    environ \
    eso-pic \
    etextools \
    etoolbox \
    fixme \
    float \
    fmtcount \
    fontspec \
    footmisc \
    framed \
    fvextra \
    gitinfo2 \
    glossaries \
    glossaries-english \
    glossaries-extra \
    ifluatex \
    ifplatform \
    impnattypo \
    l3kernel \
    l3packages \
    labelschanged \
    latex \
    latexmk \
    listofitems \
    lm \
    lm-math \
    logreq \
    luacode \
    lualatex-math \
    lualibs \
    luaotfload \
    luatex \
    luatex85 \
    luatexbase \
    makecell \
    mathfixs \
    mathtools \
    mfirstuc \
    microtype \
    minted \
    multirow \
    nag \
    nowidow \
    oberdiek \
    pdfpages \
    pdfx \
    pgf \
    pgfopts \
    pgfornament \
    pgfplots \
    placeins \
    selnolig \
    setspace \
    shapepar \
    silence \
    siunitx \
    stackengine \
    subfig \
    substr \
    supertabular \
    tabstackengine \
    tcolorbox \
    threeparttable \
    titlesec \
    tocbibind \
    todonotes \
    tools \
    tracklang \
    trimspaces \
    ulem \
    unicode-math \
    units \
    upquote \
    varwidth \
    witharrows \
    xcolor \
    xfor \
    xindy \
    xkeyval \
    xmpincl \
    xpatch \
    xstring \
    xunicode
 
