#!/bin/sh

# curl "https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh" -o dropbox_uploader.sh
# ./dropbox_uploader.sh -s upload .git/gitHeadInfo.gin Apps/Overleaf/phd_thesis/gitHeadLocal.gin
bash dropbox_uploader.sh upload .git/gitHeadInfo.gin Apps/Overleaf/phd_thesis/gitHeadLocal.gin

# rm gitHeadLocal.gin
# rm dropbox_uploader.sh

exit 0
