%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/kg314/Documents/phd_thesis_local_copy/thesis_words.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/11/11 14:36:32

%% Initialize variables.
filename = '/home/kg314/Documents/phd_thesis_local_copy/thesis_words.txt';
delimiter = ' ';

%% Format for each line of text:
%   column1: datetimes (%{yyyy-MM-dd}D)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%{yyyy-MM-dd}D%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string',  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
t = table(dataArray{1:end-1}, 'VariableNames', {'date','VarName2','VarName3','words'});

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% t.date=datenum(t.date);

%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;
dates = t.date([1:1012]); % 1012 till 03/Oct/2018 (submission date)
words = t.words([1:1012]);
set(0,'defaultaxesfontsize',12,'defaultaxeslinewidth',1.5,'defaultlinelinewidth',1.5,'defaultpatchlinewidth',2);
plot(dates,words/1000 - words(1)/1000);
xlabel('time');
ylabel("'Words' (thousands)");
title("'Word count' growth for PhD thesis draft of Krishnakumar");
export_fig -png word_count_growth_thesis.png
% cleanfigure;
% export_fig('word_count_growth.tex');